from django import forms
from .models import Goal

ICON_CHOICES = [
    ('fa-dumbbell', '🏋️'),
    ('fa-running', '🏃'),
    ('fa-biking', '🚴'),
    ('fa-swimmer', '🏊'),
    ('fa-walking', '🚶'),
    ('fa-book', '📘'),
    ('fa-graduation-cap', '🎓'),
    ('fa-pencil-alt', '✏️'),
    ('fa-laptop-code', '💻'),
    ('fa-lightbulb', '💡'),
    ('fa-apple-alt', '🍎'),
    ('fa-heartbeat', '❤️'),
    ('fa-notes-medical', '📋'),
    ('fa-weight', '⚖️'),
    ('fa-seedling', '🌱'),
    ('fa-bed', '🛏️'),
    ('fa-bath', '🛁'),
    ('fa-shower', '🚿'),
    ('fa-coffee', '☕'),
    ('fa-utensils', '🍽️'),
    ('fa-bullseye', '🎯'),
    ('fa-flag-checkered', '🏁'),
    ('fa-check-circle', '✅'),
    ('fa-calendar-check', '📅'),
    ('fa-tasks', '🗒️'),
    ('fa-music', '🎵'),
    ('fa-film', '🎬'),
    ('fa-camera', '📷'),
    ('fa-paint-brush', '🎨'),
    ('fa-gamepad', '🎮'),
    ('fa-wallet', '👛'),
    ('fa-coins', '🪙'),
    ('fa-piggy-bank', '🐷'),
    ('fa-credit-card', '💳'),
    ('fa-money-bill-wave', '💵'),
    ('fa-briefcase', '💼'),
    ('fa-chart-line', '📈'),
    ('fa-users', '👥'),
    ('fa-folder-open', '📂'),
    ('fa-clock', '⏰'),
    ('fa-mountain', '🏔️'),
    ('fa-rocket', '🚀'),
    ('fa-compass', '🧭'),
    ('fa-brain', '🧠'),
    ('fa-eye', '👁️'),
    ('fa-hiking', '🥾'),
    ('fa-leaf', '🍃'),
    ('fa-bolt', '⚡'),
    ('fa-wind', '🌬️'),
    ('fa-spa', '🧖'),
    ('fa-water', '💧'),
    ('fa-tree', '🌳'),
    ('fa-fire', '🔥'),
    ('fa-dog', '🐶'),
    ('fa-cat', '🐱'),
    ('fa-sun', '☀️'),
    ('fa-moon', '🌙'),
    ('fa-cloud', '☁️'),
    ('fa-smile', '😄'),
    ('fa-frown', '😞'),
    ('fa-meditation', '🧘'),
    ('fa-hot-tub', '🛀'),
    ('fa-om', '🕉️'),
    ('fa-peace', '☮️'),
    ('fa-campground', '🏕️'),
    ('fa-fish', '🐟'),
    ('fa-bread-slice', '🍞'),
    ('fa-egg', '🥚'),
    ('fa-carrot', '🥕'),
    ('fa-seedling-alt', '🌿'),
    ('fa-yoga', '🧘‍♂️'),
    ('fa-journal', '📓'),
    ('fa-headphones', '🎧'),
    ('fa-hourglass', '⏳'),
    ('fa-binoculars', '🔭'),
    ('fa-calendar-alt', '📆'),
    ('fa-smog', '🌫️'),
    ('fa-snowflake', '❄️'),
    ('fa-bug', '🐞'),
    ('fa-plane', '✈️'),
    ('fa-ship', '🚢'),
    ('fa-bus', '🚌'),
    ('fa-bicycle', '🚲'),
    ('fa-anchor', '⚓'),
    ('fa-camera-retro', '📸'),
    ('fa-microphone', '🎤'),
    ('fa-drum', '🥁'),
    ('fa-guitar', '🎸'),
    ('fa-star', '⭐'),
    ('fa-heart', '💖'),
    ('fa-handshake', '🤝'),
    ('fa-bell', '🔔'),
    ('fa-birthday-cake', '🎂'),
    ('fa-cookie', '🍪'),
    ('fa-lemon', '🍋'),
    ('fa-ice-cream', '🍨'),
    ('fa-hamburger', '🍔'),
    ('fa-bacon', '🥓'),
    ('fa-pizza-slice', '🍕'),
    ('fa-cocktail', '🍸'),
    ('fa-wine-glass', '🍷')
]

class GoalForm(forms.ModelForm):
    icon = forms.ChoiceField(choices=ICON_CHOICES, label="アイコン")

    class Meta:
        model = Goal
        fields = ['title', 'icon']
        labels = {
            'title': '目標のタイトル',
        }
