# Generated by Django 5.1.6 on 2025-03-31 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='actual_count',
        ),
    ]
