# Generated by Django 5.1.6 on 2025-04-16 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_name', models.CharField(max_length=100)),
                ('schedule_days', models.CharField(max_length=50)),
                ('target_value', models.PositiveIntegerField(default=1)),
                ('target_frequency', models.CharField(choices=[('1日あたり', '1日あたり'), ('1週間あたり', '1週間あたり'), ('1ヶ月あたり', '1ヶ月あたり')], default='1日あたり', max_length=20)),
                ('target_unit', models.CharField(choices=[('回', '回'), ('分', '分'), ('時間', '時間'), ('ml', 'ミリリットル'), ('l', 'リットル'), ('km', 'キロメートル'), ('mile', 'マイル'), ('㎎', 'グラム')], default='回', max_length=20)),
                ('icon', models.CharField(default='fa-star', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=False)),
                ('status', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
            ],
        ),
    ]
