# Generated by Django 5.1.6 on 2025-04-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='icon',
        ),
    ]
