# Generated by Django 5.1.6 on 2025-04-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
