# Generated by Django 5.1.6 on 2025-04-24 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('habits', '0002_remove_habit_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='icon',
            field=models.CharField(default='fa-star', max_length=50),
        ),
        migrations.AlterField(
            model_name='habit',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.goal'),
        ),
    ]
