# Generated by Django 5.1.6 on 2025-04-04 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_remove_goal_actual_count'),
        ('habits', '0003_dailyreport_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.goal'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='habit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit'),
        ),
    ]
