# Generated by Django 5.1.6 on 2025-04-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_dailyreport_goal_alter_dailyreport_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
